# Generated by Django 5.2.9 on 2026-02-17 04:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(db_index=True, max_length=20)),
                ('network', models.CharField(choices=[('MTN', 'MTN'), ('VOD', 'Telecel (Vodafone)'), ('AIR', 'AirtelTigo')], max_length=5)),
                ('verified_name', models.CharField(help_text='Name returned by Orchard AII verification', max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momo_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['player', 'is_active'], name='payments_mo_player__bda6ed_idx')],
                'unique_together': {('player', 'mobile_number')},
            },
        ),
    ]
