# Generated by Django 5.2.9 on 2026-02-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_players', models.PositiveIntegerField(default=0)),
                ('new_players', models.PositiveIntegerField(default=0)),
                ('active_players', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('total_flips', models.PositiveIntegerField(default=0)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_stakes', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_payouts', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('house_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actual_house_edge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_referral_bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ad_impressions', models.PositiveIntegerField(default=0)),
                ('ad_clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Statistics',
                'verbose_name_plural': 'Daily Statistics',
                'ordering': ['-date'],
            },
        ),
    ]
