# Generated by Django 5.2.9 on 2026-02-17 04:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('advertiser', models.CharField(blank=True, default='', max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_enabled', models.BooleanField(default=False)),
                ('show_every_n_flips', models.PositiveIntegerField(default=5, help_text='Show ad every N flips')),
                ('max_ads_per_session', models.PositiveIntegerField(default=3)),
                ('skip_after_seconds', models.PositiveIntegerField(default=5, help_text='Allow skipping ad after this many seconds')),
                ('non_blocking', models.BooleanField(default=True, help_text='If True, ads appear as overlay without pausing gameplay')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad Configuration',
                'verbose_name_plural': 'Ad Configuration',
            },
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('html', 'HTML')], default='image', max_length=10)),
                ('media_file', models.FileField(upload_to='ads/')),
                ('click_url', models.URLField(blank=True, default='')),
                ('duration_seconds', models.PositiveIntegerField(default=5)),
                ('display_position', models.CharField(choices=[('between_flips', 'Between Flips'), ('sidebar', 'Sidebar'), ('overlay', 'Overlay')], default='between_flips', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='ads.adcampaign')),
            ],
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='ads.adcreative')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gamesession')),
            ],
            options={
                'ordering': ['-shown_at'],
            },
        ),
    ]
