# Generated by Django 5.2.9 on 2026-02-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_otp_enabled', models.BooleanField(default=True, help_text='Enable SMS OTP login')),
                ('whatsapp_otp_enabled', models.BooleanField(default=True, help_text='Enable WhatsApp OTP login')),
                ('google_enabled', models.BooleanField(default=False, help_text='Enable Google OAuth login')),
                ('facebook_enabled', models.BooleanField(default=False, help_text='Enable Facebook OAuth login')),
                ('otp_expiry_minutes', models.PositiveIntegerField(default=5, help_text='OTP code expiry in minutes')),
                ('max_otp_per_hour', models.PositiveIntegerField(default=6, help_text='Max OTP requests per phone per hour')),
                ('maintenance_message', models.CharField(blank=True, default='', help_text='Message shown when a login method is disabled (blank = generic)', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auth Configuration',
                'verbose_name_plural': 'Auth Configuration',
            },
        ),
    ]
