# Generated by Django 5.2.9 on 2026-02-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='authconfig',
            name='email_password_enabled',
            field=models.BooleanField(default=False, help_text='Enable email/password signup & login'),
        ),
        migrations.AlterField(
            model_name='player',
            name='auth_provider',
            field=models.CharField(choices=[('phone', 'Phone OTP'), ('email', 'Email/Password'), ('google', 'Google'), ('facebook', 'Facebook')], default='phone', max_length=20),
        ),
    ]
