# Generated by Django 5.2.9 on 2026-02-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_email_password_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name (e.g. "Twilio Primary")', max_length=50)),
                ('provider_type', models.CharField(choices=[('twilio', 'Twilio'), ('arkesel', 'Arkesel'), ('hubtel', 'Hubtel'), ('mnotify', 'mNotify'), ('wigal', 'Wigal')], max_length=20)),
                ('api_key', models.CharField(help_text='API key / Account SID', max_length=500)),
                ('api_secret', models.CharField(blank=True, default='', help_text='API secret / Auth token (blank if not needed)', max_length=500)),
                ('sender_id', models.CharField(default='CASHFLIP', help_text='Alphanumeric sender ID or phone number', max_length=20)),
                ('base_url', models.URLField(blank=True, default='', help_text='API base URL (blank = use provider default)')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority = tried first. Providers are tried in descending priority order.')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='Provider-specific config JSON (e.g. {"fallback_number": "+1234567890"})')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Provider',
                'verbose_name_plural': 'SMS Providers',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
