# Generated by Django 5.2.9 on 2026-02-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_launch_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='provider_type',
            field=models.CharField(blank=True, default='', help_text='SMS provider type used (e.g. twilio_verify, arkesel). Empty = legacy/whatsapp.', max_length=20),
        ),
        migrations.AlterField(
            model_name='smsprovider',
            name='provider_type',
            field=models.CharField(choices=[('twilio', 'Twilio (Messages API)'), ('twilio_verify', 'Twilio Verify'), ('arkesel', 'Arkesel'), ('hubtel', 'Hubtel'), ('mnotify', 'mNotify'), ('wigal', 'Wigal')], max_length=20),
        ),
    ]
