# Generated by Django 5.2.9 on 2026-02-17 04:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('locked_balance', models.DecimalField(decimal_places=2, default=0, help_text='Balance locked in active game sessions', max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='game.currency')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tx_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('stake', 'Game Stake'), ('win', 'Game Win'), ('cashout', 'Cashout'), ('pause_fee', 'Pause Fee'), ('referral_bonus', 'Referral Bonus'), ('ad_bonus', 'Ad Bonus'), ('admin_credit', 'Admin Credit'), ('admin_debit', 'Admin Debit')], db_index=True, max_length=20)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='completed', max_length=15)),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'tx_type'], name='wallet_wall_wallet__5194bc_idx'), models.Index(fields=['created_at'], name='wallet_wall_created_929d33_idx')],
            },
        ),
    ]
