# Generated by Django 5.2.9 on 2026-02-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transfer_tx_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='tx_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('stake', 'Game Stake'), ('win', 'Game Win'), ('cashout', 'Cashout'), ('pause_fee', 'Pause Fee'), ('referral_bonus', 'Referral Bonus'), ('ad_bonus', 'Ad Bonus'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('admin_credit', 'Admin Credit'), ('admin_debit', 'Admin Debit'), ('voucher', 'Voucher Redemption')], db_index=True, max_length=20),
        ),
    ]
