# Generated by Django 5.2.9 on 2026-02-17 04:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['-is_default', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banknote_image', models.ImageField(blank=True, help_text='Upload banknote image for this denomination', null=True, upload_to='banknotes/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_zero', models.BooleanField(default=False, help_text='Is this the zero/loss denomination?')),
                ('is_active', models.BooleanField(default=True)),
                ('weight', models.PositiveIntegerField(default=10, help_text='Relative weight for random selection (higher = more frequent)')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denominations', to='game.currency')),
            ],
            options={
                'ordering': ['currency', 'display_order', 'value'],
                'unique_together': {('currency', 'value')},
            },
        ),
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_edge_percent', models.DecimalField(decimal_places=2, default=60.0, help_text='House retention percentage (e.g. 60 = house keeps 60%)', max_digits=5)),
                ('min_deposit', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('max_cashout', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('min_stake', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('pause_cost_percent', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage of cashout balance charged to pause', max_digits=5)),
                ('zero_base_rate', models.DecimalField(decimal_places=4, default=0.05, help_text='Base probability of zero (0.05 = 5%)', max_digits=5)),
                ('zero_growth_rate', models.DecimalField(decimal_places=4, default=0.08, help_text='Growth factor k for zero probability curve', max_digits=5)),
                ('min_flips_before_zero', models.PositiveIntegerField(default=2, help_text='Guaranteed safe flips before zero can appear')),
                ('max_session_duration_minutes', models.PositiveIntegerField(default=120)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_config', to='game.currency')),
            ],
            options={
                'verbose_name': 'Game Configuration',
                'verbose_name_plural': 'Game Configurations',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stake_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cashout_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cashed_out', 'Cashed Out'), ('lost', 'Lost'), ('paused', 'Paused'), ('expired', 'Expired')], db_index=True, default='active', max_length=15)),
                ('flip_count', models.PositiveIntegerField(default=0)),
                ('server_seed', models.CharField(blank=True, default='', max_length=64)),
                ('server_seed_hash', models.CharField(blank=True, default='', max_length=64)),
                ('client_seed', models.CharField(blank=True, default='', max_length=64)),
                ('nonce', models.PositiveIntegerField(default=0)),
                ('pause_fee_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='game.currency')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlipResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flip_number', models.PositiveIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_zero', models.BooleanField(default=False)),
                ('cumulative_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('result_hash', models.CharField(blank=True, default='', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('denomination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.currencydenomination')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flips', to='game.gamesession')),
            ],
            options={
                'ordering': ['session', 'flip_number'],
            },
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['player', 'status'], name='game_gamese_player__bd8652_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flipresult',
            unique_together={('session', 'flip_number')},
        ),
    ]
