# Generated by Django 5.2.9 on 2026-02-17 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedGameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Test Config', help_text='Label for this test scenario', max_length=100)),
                ('is_enabled', models.BooleanField(db_index=True, default=False, help_text='Master switch — enable to activate simulation mode')),
                ('outcome_mode', models.CharField(choices=[('normal', 'Normal (no override)'), ('always_win', 'Always Win (never zero)'), ('always_lose', 'Always Lose (always zero)'), ('force_zero_at', 'Force Zero at Specific Flip Number'), ('fixed_probability', 'Fixed Zero Probability (override curve)'), ('streak_then_lose', 'Win Streak Then Lose (win N flips, then zero)')], default='normal', help_text='How flip outcomes are determined', max_length=20)),
                ('force_zero_at_flip', models.PositiveIntegerField(blank=True, default=0, help_text='Force zero on this flip number (for force_zero_at mode)')),
                ('fixed_zero_probability', models.DecimalField(decimal_places=4, default=0, help_text='Fixed probability 0.0–1.0 (for fixed_probability mode)', max_digits=5)),
                ('win_streak_length', models.PositiveIntegerField(default=5, help_text='Number of guaranteed wins before forced loss (streak_then_lose mode)')),
                ('force_denomination_value', models.DecimalField(blank=True, decimal_places=2, help_text='Force this denomination value on every win flip (blank = random)', max_digits=10, null=True)),
                ('apply_to_all_players', models.BooleanField(default=True, help_text='Apply to all players, or only targeted players below')),
                ('override_min_stake', models.DecimalField(blank=True, decimal_places=2, help_text='Override min stake for test (blank = use normal config)', max_digits=10, null=True)),
                ('override_max_cashout', models.DecimalField(blank=True, decimal_places=2, help_text='Override max cashout for test (blank = use normal config)', max_digits=12, null=True)),
                ('grant_test_balance', models.DecimalField(decimal_places=2, default=0, help_text='Auto-grant this balance to targeted players on session start (0 = disabled)', max_digits=12)),
                ('auto_disable_after', models.PositiveIntegerField(default=0, help_text='Auto-disable after N game sessions (0 = never)')),
                ('sessions_used', models.PositiveIntegerField(default=0, editable=False, help_text='Sessions played under this config')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes about this test scenario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('targeted_players', models.ManyToManyField(blank=True, help_text='If not apply_to_all, only these players get simulation', related_name='simulated_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulated Game Config',
                'verbose_name_plural': 'Simulated Game Configs',
                'ordering': ['-is_enabled', '-updated_at'],
            },
        ),
    ]
