# Generated by Django 5.2.9 on 2026-02-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_simulatedgameconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, default='', help_text='Main logo (SVG/PNG). Default: static/images/cashflip-logo.svg', upload_to='branding/')),
                ('logo_icon', models.FileField(blank=True, default='', help_text='Square icon/favicon (SVG/PNG). Default: static/images/cashflip-icon.svg', upload_to='branding/')),
                ('loading_animation', models.FileField(blank=True, default='', help_text='Loading screen animation (GIF/SVG). Blank = CSS glow default', upload_to='branding/')),
                ('primary_color', models.CharField(default='#00BFA6', help_text='Electric Teal', max_length=7)),
                ('secondary_color', models.CharField(default='#F5C842', help_text='Rich Gold', max_length=7)),
                ('accent_color', models.CharField(default='#00E676', help_text='Lime Flash (success)', max_length=7)),
                ('background_color', models.CharField(default='#0D1117', help_text='Midnight Obsidian', max_length=7)),
                ('tagline', models.CharField(default='Flip Notes. Stack Cash. Win Big.', help_text='Displayed on auth/loading screens', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Branding',
                'verbose_name_plural': 'Site Branding',
            },
        ),
    ]
