# Generated by Django 5.2.9 on 2026-02-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_sitebranding'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfig',
            name='simulated_feed_data',
            field=models.JSONField(blank=True, default=list, help_text='Simulated feed entries: [{"player":"Luc**er","won":true,"amount":"50.00","flips":5}]'),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='simulated_feed_enabled',
            field=models.BooleanField(default=False, help_text='Enable simulated live feed for demo/pitching (fake leaderboard entries)'),
        ),
    ]
