# Generated by Django 5.2.9 on 2026-02-17 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_simulated_feed_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('first_win', 'First Win'), ('streak_3', '3-Win Streak'), ('streak_5', '5-Win Streak'), ('streak_7', '7-Win Streak'), ('high_roller', 'High Roller (₵100+ stake)'), ('big_cashout', 'Big Cashout (₵50+)'), ('mega_cashout', 'Mega Cashout (₵200+)'), ('flip_master', 'Flip Master (100 flips)'), ('veteran', 'Veteran (50 sessions)'), ('daily_player', 'Daily Player (7 day streak)'), ('lucky_7', 'Lucky 7 (won on flip #7)'), ('whale', 'Whale (₵500+ single stake)'), ('social', 'Social (referred a friend)'), ('depositor', 'First Deposit')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('emoji', models.CharField(default='🏆', max_length=10)),
                ('xp_value', models.PositiveIntegerField(default=10, help_text='XP points awarded')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DailyBonusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('segments', models.JSONField(blank=True, default=list, help_text='Wheel segments: [{"label":"₵0.50","value":0.50,"color":"#ffd700","weight":30}, ...]')),
                ('cooldown_hours', models.PositiveIntegerField(default=24, help_text='Hours between spins')),
                ('max_spins_per_day', models.PositiveIntegerField(default=1)),
                ('require_deposit', models.BooleanField(default=False, help_text='Require at least one deposit to spin')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Bonus Config',
            },
        ),
        migrations.CreateModel(
            name='FeatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badges_enabled', models.BooleanField(default=True, help_text='Achievement badges system')),
                ('daily_wheel_enabled', models.BooleanField(default=True, help_text='Daily bonus wheel')),
                ('sounds_enabled', models.BooleanField(default=True, help_text='Casino sound effects')),
                ('haptics_enabled', models.BooleanField(default=True, help_text='Mobile haptic feedback')),
                ('social_proof_enabled', models.BooleanField(default=True, help_text='Live win toast notifications')),
                ('streak_badge_enabled', models.BooleanField(default=True, help_text='Win streak fire badge')),
                ('confetti_enabled', models.BooleanField(default=True, help_text='Win/loss confetti particles')),
                ('deposit_sound_enabled', models.BooleanField(default=True, help_text='Soothing sound on deposit CTA')),
                ('social_proof_min_amount', models.DecimalField(decimal_places=2, default=10.0, help_text='Minimum win amount to show social proof toast', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Configuration',
            },
        ),
        migrations.CreateModel(
            name='DailyBonusSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('segment_label', models.CharField(max_length=50)),
                ('spun_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_spins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-spun_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='game.badge')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gamesession')),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('player', 'badge')},
            },
        ),
    ]
