# Generated by Django 5.2.9 on 2026-02-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_badges_wheel_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfig',
            name='auto_flip_seconds',
            field=models.PositiveIntegerField(default=8, help_text='Seconds before auto-flip triggers if player idles (0 = disabled)'),
        ),
    ]
