# Generated by Django 5.2.9 on 2026-02-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_flip_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencydenomination',
            name='banknote_image',
        ),
        migrations.AddField(
            model_name='currencydenomination',
            name='back_image',
            field=models.ImageField(blank=True, help_text='Back side of the banknote', null=True, upload_to='banknotes/back/'),
        ),
        migrations.AddField(
            model_name='currencydenomination',
            name='front_image',
            field=models.ImageField(blank=True, help_text='Front side of the banknote', null=True, upload_to='banknotes/front/'),
        ),
    ]
