# Generated by Django 5.2.9 on 2026-02-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_rename_banknote_to_front_back_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencydenomination',
            name='face_image_path',
            field=models.CharField(blank=True, default='', help_text='Static path to face image, e.g. images/Cedi-Face/5f.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='currencydenomination',
            name='flip_sequence_frames',
            field=models.PositiveIntegerField(default=31, help_text='Number of frames in the flip sequence (0-indexed PNGs)'),
        ),
        migrations.AddField(
            model_name='currencydenomination',
            name='flip_sequence_prefix',
            field=models.CharField(blank=True, default='', help_text='Static path to flip sequence folder, e.g. images/Cedi-Sequences/5', max_length=255),
        ),
        migrations.AddField(
            model_name='currencydenomination',
            name='payout_multiplier',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Payout as % of stake per flip. E.g. 8 = each flip adds 8% of stake. Tune so that avg_multiplier × expected_flips < 100 for house edge.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='currencydenomination',
            name='back_image',
            field=models.ImageField(blank=True, help_text='Back side of the banknote. Recommended: 960×510 px (2x) or 1440×765 px (3x), PNG/JPEG, < 200KB', null=True, upload_to='banknotes/back/'),
        ),
        migrations.AlterField(
            model_name='currencydenomination',
            name='front_image',
            field=models.ImageField(blank=True, help_text='Front side of the banknote. Recommended: 960×510 px (2x) or 1440×765 px (3x), PNG/JPEG, < 200KB', null=True, upload_to='banknotes/front/'),
        ),
        migrations.AlterField(
            model_name='currencydenomination',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Face value of the note (visual only, e.g. 1, 5, 10, 50)', max_digits=10),
        ),
    ]
