# Generated by Django 5.2.9 on 2026-02-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_add_denomination_multiplier_and_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencydenomination',
            name='flip_gif_path',
            field=models.CharField(blank=True, default='', help_text='Static path to flip GIF, e.g. images/Cedi-Gifs/5cedis.gif', max_length=255),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='flip_animation_mode',
            field=models.CharField(choices=[('gif', 'GIF Animation'), ('png', 'PNG Sequence')], default='gif', help_text='Which animation format to use for note flips', max_length=10),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='flip_animation_speed_ms',
            field=models.PositiveIntegerField(default=1500, help_text='Duration of the flip animation in milliseconds (e.g. 1500 = 1.5s)'),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='flip_sound_enabled',
            field=models.BooleanField(default=True, help_text='Play money-flipping sound during flip animation'),
        ),
    ]
