# Generated by Django 5.2.9 on 2026-02-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_add_flip_gif_and_animation_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencydenomination',
            name='face_image_upload',
            field=models.FileField(blank=True, help_text='Upload face image (JPG/PNG). Takes priority over face_image_path. 1920×1080 recommended.', null=True, upload_to='banknotes/faces/'),
        ),
        migrations.AddField(
            model_name='currencydenomination',
            name='flip_gif_upload',
            field=models.FileField(blank=True, help_text='Upload flip animation GIF. Takes priority over flip_gif_path. 1920×1080 recommended.', null=True, upload_to='banknotes/gifs/'),
        ),
        migrations.AlterField(
            model_name='currencydenomination',
            name='face_image_path',
            field=models.CharField(blank=True, default='', help_text='Static path to face image, e.g. images/Cedi-Face/5f.jpg (fallback if no upload)', max_length=255),
        ),
        migrations.AlterField(
            model_name='currencydenomination',
            name='flip_gif_path',
            field=models.CharField(blank=True, default='', help_text='Static path to flip GIF, e.g. images/Cedi-Gifs/5cedis.gif (fallback if no upload)', max_length=255),
        ),
    ]
