# Generated by Django 5.2.9 on 2026-02-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_add_face_and_gif_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfig',
            name='flip_display_mode',
            field=models.CharField(choices=[('face_then_gif', 'Face Image then GIF'), ('gif_only', 'GIF Only (static first frame)')], default='face_then_gif', help_text='face_then_gif = show face JPG then play GIF on flip. gif_only = show GIF first frame as static, play full GIF on flip.', max_length=20),
        ),
    ]
