# Generated by Django 5.2.9 on 2026-02-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_add_flip_display_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfig',
            name='instant_cashout_enabled',
            field=models.BooleanField(default=True, help_text='Allow players to send winnings directly to MoMo on cashout'),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='instant_cashout_min_amount',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Minimum cashout amount eligible for instant MoMo payout', max_digits=10),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='min_flips_before_cashout',
            field=models.PositiveIntegerField(default=3, help_text='Minimum flips required before player can cash out (prevents risk-free profit)'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='age_restriction_text',
            field=models.CharField(default='18+', help_text='Age restriction badge text', max_length=10),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='regulatory_logo',
            field=models.FileField(blank=True, default='', help_text='Gaming commission logo (SVG/PNG). Default: static/images/Ghana-Gaming-Commission-logo.png', upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='regulatory_text',
            field=models.CharField(default='Regulated by the Gaming Commission of Ghana', help_text='Text displayed alongside the regulatory logo', max_length=300),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='responsible_gaming_text',
            field=models.CharField(default='Bet Responsibly', help_text='Responsible gaming message', max_length=200),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='show_regulatory_footer',
            field=models.BooleanField(default=True, help_text='Show regulatory footer on auth/landing screens'),
        ),
    ]
