# Generated by Django 5.2.9 on 2026-02-21 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_launch_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencydenomination',
            name='boost_payout_multiplier',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Payout multiplier used in boost mode (0 = auto-calculated from normal × boost_multiplier_factor)', max_digits=6),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='boost_multiplier_factor',
            field=models.DecimalField(decimal_places=2, default=1.33, help_text='Factor to multiply normal multipliers by in boost mode (1.33 = 33% increase)', max_digits=4),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='boost_payout_target',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Target player payout % in boost mode (40 = players get back 40% of stakes)', max_digits=5),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='normal_payout_target',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Target player payout % in normal mode (30 = players get back 30% of stakes)', max_digits=5),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='payout_mode',
            field=models.CharField(choices=[('normal', 'Normal'), ('boost', 'Boost')], default='normal', help_text='Normal = 70/30 house/player split. Boost = 60/40 (use when participation is down)', max_length=10),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='house_edge_percent',
            field=models.DecimalField(decimal_places=2, default=70.0, help_text='House retention percentage (e.g. 70 = house keeps 70%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='min_deposit',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='min_stake',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='StakeTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tier display name (e.g. Standard, Premium, VIP)', max_length=50)),
                ('min_stake', models.DecimalField(decimal_places=2, help_text='Minimum stake for this tier (inclusive)', max_digits=12)),
                ('max_stake', models.DecimalField(decimal_places=2, help_text='Maximum stake for this tier (inclusive)', max_digits=12)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stake_tiers', to='game.currency')),
                ('denominations', models.ManyToManyField(blank=True, help_text='Which denominations appear when playing at this stake level', related_name='stake_tiers', to='game.currencydenomination')),
            ],
            options={
                'verbose_name': 'Stake Tier',
                'verbose_name_plural': 'Stake Tiers',
                'ordering': ['currency', 'display_order', 'min_stake'],
            },
        ),
    ]
