# Generated by Django 5.2.9 on 2026-02-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_stake_tiers_and_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebranding',
            name='loading_animation_cloud_url',
            field=models.URLField(blank=True, default='', help_text='Cloudinary URL for loading animation (overrides loading_animation FileField)', max_length=500),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='logo_cloud_url',
            field=models.URLField(blank=True, default='', help_text='Cloudinary URL for main logo (overrides logo FileField)', max_length=500),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='logo_icon_cloud_url',
            field=models.URLField(blank=True, default='', help_text='Cloudinary URL for icon/favicon (overrides logo_icon FileField)', max_length=500),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='regulatory_logo_cloud_url',
            field=models.URLField(blank=True, default='', help_text='Cloudinary URL for regulatory logo', max_length=500),
        ),
    ]
