# Generated by Django 5.2.9 on 2026-02-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_branding_cloud_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencydenomination',
            name='flip_video_path',
            field=models.CharField(blank=True, default='', help_text='Path or Cloudinary URL to flip MP4/WebM video, e.g. videos/5cedis.mp4', max_length=500),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='decay_factor',
            field=models.DecimalField(decimal_places=4, default=0.05, help_text='Decay factor k for exponential weight curve. Small k=equal payouts, large k=front-loaded. Formula: weight_i = e^(-k * (i-1))', max_digits=6),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='holiday_boost_pct',
            field=models.DecimalField(decimal_places=2, default=70.0, help_text='Payout percentage for holiday-boosted players (e.g. 70 = they get 70% back instead of 40%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='holiday_frequency',
            field=models.PositiveIntegerField(default=1000, help_text='1 in N active players gets the holiday boost (e.g. 1000 = 0.1% chance)'),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='holiday_max_tier_name',
            field=models.CharField(blank=True, default='Standard', help_text='Only players in this tier or lower get holiday boost (empty = all tiers)', max_length=50),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='holiday_mode_enabled',
            field=models.BooleanField(default=False, help_text='Enable Holiday trigger: randomly boost payout for selected low-stake players'),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='max_flips_per_session',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of flips allowed per session (budget may end sooner)'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='is_holiday_boosted',
            field=models.BooleanField(default=False, help_text='Whether this session received the holiday boost'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='payout_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total payout budget for this session = stake × payout_pct. Denomination face values deducted from this.', max_digits=12),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='payout_pct_used',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The actual payout percentage used for this session (may be boosted by holiday trigger)', max_digits=5),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='remaining_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining payout budget (decreases as player flips). Zero when exhausted.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='flip_animation_mode',
            field=models.CharField(choices=[('gif', 'GIF Animation'), ('png', 'PNG Sequence'), ('video', 'MP4/WebM Video')], default='gif', help_text='Which animation format to use for note flips', max_length=10),
        ),
    ]
