# Generated by Django 5.2.9 on 2026-02-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_wysiwyg_engine_and_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfig',
            name='flip_sound_url',
            field=models.URLField(blank=True, default='', help_text='Custom flip sound URL (Cloudinary). Empty = use default /static/sounds/money-flip.mp3', max_length=500),
        ),
    ]
