# Generated by Django 5.2.9 on 2026-02-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_flip_sound_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfig',
            name='card_back_image_url',
            field=models.URLField(blank=True, default='', help_text='Card back image URL (Cloudinary). Shown before flip — denomination revealed by animation. Empty = gradient fallback.', max_length=500),
        ),
    ]
