# Generated by Django 5.2.9 on 2026-02-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_card_back_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameconfig',
            old_name='card_back_image_url',
            new_name='start_flip_image_url',
        ),
    ]
