# Generated by Django 5.2.9 on 2026-02-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_rename_card_back_to_start_flip_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameconfig',
            name='flip_animation_mode',
            field=models.CharField(choices=[('css3d', 'CSS 3D Flip'), ('gif', 'GIF Animation'), ('png', 'PNG Sequence'), ('video', 'MP4/WebM Video')], default='css3d', help_text='Which animation format to use for note flips', max_length=10),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='start_flip_image_url',
            field=models.URLField(blank=True, default='', help_text='Image shown on the first card when a new session starts (Cloudinary). Subsequent cards show denomination glimpses.', max_length=500),
        ),
    ]
