# Generated by Django 5.2.9 on 2026-02-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_add_css3d_flip_animation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfig',
            name='cashout_sound_url',
            field=models.URLField(blank=True, default='', help_text='Custom cashout celebration sound URL. Empty = use default /static/sounds/money-cashout.mp3', max_length=500),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='win_sound_url',
            field=models.URLField(blank=True, default='', help_text='Custom win celebration sound URL. Empty = use default /static/sounds/money-win.mp3', max_length=500),
        ),
    ]
