# Generated by Django 5.2.9 on 2026-02-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_add_win_and_cashout_sound_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy', models.TextField(blank=True, default='', help_text='Privacy Policy content (HTML)')),
                ('terms_of_service', models.TextField(blank=True, default='', help_text='Terms of Service content (HTML)')),
                ('sms_disclosure', models.TextField(blank=True, default='By providing your phone number, you consent to receive a one-time verification code via SMS. Standard message and data rates may apply. Carriers are not liable for delayed or undelivered messages.', help_text='SMS/messaging disclosure shown on login screen')),
                ('support_email', models.EmailField(blank=True, default='support@cashflip.cash', help_text='Support email shown in legal docs', max_length=254)),
                ('support_phone', models.CharField(blank=True, default='', help_text='Support phone shown in legal docs', max_length=30)),
                ('company_name', models.CharField(blank=True, default='CashFlip', help_text='Legal company name', max_length=200)),
                ('company_address', models.TextField(blank=True, default='', help_text='Registered company address')),
                ('license_info', models.TextField(blank=True, default='Licensed and regulated by the Gaming Commission of Ghana.', help_text='License/regulatory information')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
            },
        ),
    ]
