# Generated by Django 5.2.9 on 2026-02-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_legal_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfig',
            name='flip_sprite_frames',
            field=models.PositiveIntegerField(default=22, help_text='Number of frames in the sprite sheet (horizontal strip)'),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='flip_sprite_url',
            field=models.URLField(blank=True, default='', help_text='URL to universal flip sprite sheet (WebP). Empty = use default /static/images/assets/flip_motion_sprite.webp', max_length=500),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='flip_animation_mode',
            field=models.CharField(choices=[('sprite', 'Universal Sprite'), ('css3d', 'CSS 3D Flip'), ('gif', 'GIF Animation'), ('png', 'PNG Sequence'), ('video', 'MP4/WebM Video (deprecated)')], default='sprite', help_text='Which animation format to use for note flips', max_length=10),
        ),
    ]
