# Generated by Django 5.2.9 on 2026-02-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_sprite_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfig',
            name='flip_sprite_fps',
            field=models.PositiveIntegerField(default=25, help_text='Frames per second for sprite playback (e.g. 20, 25, 30). Higher = faster animation.'),
        ),
    ]
