# Generated by Django 5.2.9 on 2026-02-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_sprite_fps'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencydenomination',
            name='flip_sprite_path',
            field=models.CharField(blank=True, default='', help_text='URL or static path to denomination flip sprite (WebP). E.g. /static/images/assets/sprites/5cedi_flip.webp or Cloudinary URL', max_length=500),
        ),
    ]
