# Generated by Django 5.2.9 on 2026-02-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_denom_sprite_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfig',
            name='withdrawal_enabled',
            field=models.BooleanField(default=True, help_text='Allow players to withdraw. Disable during maintenance or payout delays.'),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='withdrawal_paused_message',
            field=models.CharField(blank=True, default='Withdrawals are temporarily paused for maintenance. Your balance is safe and will be available shortly.', help_text='Friendly message shown to players when withdrawals are paused.', max_length=500),
        ),
    ]
