# Generated by Django 5.2.9 on 2026-02-22 03:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Batch label, e.g. "Launch Promo 5 GHS"', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Credit amount per voucher', max_digits=12)),
                ('currency_code', models.CharField(default='GHS', max_length=5)),
                ('quantity', models.PositiveIntegerField(help_text='Number of vouchers in batch')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry for all vouchers in batch', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voucher_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'voucher batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Credit amount when redeemed', max_digits=12)),
                ('currency_code', models.CharField(default='GHS', max_length=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('disabled', 'Disabled')], db_index=True, default='active', max_length=10)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL)),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_vouchers', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='vouchers.voucherbatch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'code'], name='vouchers_vo_status_cfb5f1_idx')],
            },
        ),
    ]
