# Generated by Django 5.2.9 on 2026-02-17 06:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0003_sitebranding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Brand name (e.g. Elitebet)', max_length=200)),
                ('slug', models.SlugField(help_text='URL-safe identifier', unique=True)),
                ('website', models.URLField(blank=True, default='', help_text='e.g. https://elitebetgh.com')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('deactivated', 'Deactivated')], db_index=True, default='pending', max_length=15)),
                ('debit_url', models.URLField(blank=True, default='', help_text='Operator endpoint we call to debit player on bet')),
                ('credit_url', models.URLField(blank=True, default='', help_text='Operator endpoint we call to credit player on win')),
                ('rollback_url', models.URLField(blank=True, default='', help_text='Operator endpoint we call to rollback a failed debit')),
                ('wallet_auth_token', models.CharField(blank=True, default='', help_text='Bearer token we send when calling operator wallet URLs', max_length=500)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=20.0, help_text='Cashflip keeps this % of GGR (e.g. 20.00)', max_digits=5)),
                ('settlement_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('min_settlement_amount', models.DecimalField(decimal_places=2, default=100.0, help_text='Minimum GGR before settlement is generated', max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OperatorAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='Default', help_text='Label for this key', max_length=100)),
                ('api_key', models.CharField(db_index=True, help_text='Public API key sent in X-API-Key header', max_length=64, unique=True)),
                ('api_secret', models.CharField(help_text='HMAC secret for signing', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=120, help_text='Max requests per minute')),
                ('ip_whitelist', models.JSONField(blank=True, default=list, help_text='List of allowed IPs (empty = allow all)')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='partner.operator')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperatorBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', help_text='Name shown on loading screen (defaults to operator name)', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Operator logo for iframe loader', upload_to='partner/branding/')),
                ('loading_animation', models.FileField(blank=True, help_text='Loading animation (GIF/SVG). Blank = Cashflip default', upload_to='partner/branding/')),
                ('primary_color', models.CharField(default='#000000', help_text='Operator primary brand color', max_length=7)),
                ('accent_color', models.CharField(default='#F5C842', help_text='Accent color', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='partner.operator')),
            ],
            options={
                'verbose_name': 'Operator Branding',
                'verbose_name_plural': 'Operator Brandings',
            },
        ),
        migrations.CreateModel(
            name='OperatorGameConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_edge_percent', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('min_stake', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('max_stake', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('max_cashout', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('zero_base_rate', models.DecimalField(decimal_places=4, default=0.05, max_digits=5)),
                ('zero_growth_rate', models.DecimalField(decimal_places=4, default=0.08, max_digits=5)),
                ('min_flips_before_zero', models.PositiveIntegerField(default=2)),
                ('pause_cost_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('max_session_duration_minutes', models.PositiveIntegerField(default=120)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(help_text='Currency this operator uses', on_delete=django.db.models.deletion.PROTECT, to='game.currency')),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_config', to='partner.operator')),
            ],
            options={
                'verbose_name': 'Operator Game Config',
                'verbose_name_plural': 'Operator Game Configs',
            },
        ),
        migrations.CreateModel(
            name='OperatorPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ext_player_id', models.CharField(db_index=True, help_text="Player ID in the operator's system", max_length=200)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='partner.operator')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_mappings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperatorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ext_session_ref', models.CharField(blank=True, default='', help_text='External reference from operator', max_length=200)),
                ('debit_tx_ref', models.CharField(blank=True, default='', help_text='Our tx ref for the debit call', max_length=100)),
                ('credit_tx_ref', models.CharField(blank=True, default='', help_text='Our tx ref for the credit call', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_session', to='game.gamesession')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='partner.operator')),
                ('operator_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='partner.operatorplayer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperatorSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_bets', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_wins', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('ggr', models.DecimalField(decimal_places=2, default=0, help_text='Gross Gaming Revenue = total_bets - total_wins', max_digits=14)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, help_text='Snapshot of rate at settlement time', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount Cashflip keeps', max_digits=14)),
                ('net_operator_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount due to operator', max_digits=14)),
                ('currency_code', models.CharField(default='GHS', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('paid', 'Paid'), ('disputed', 'Disputed')], db_index=True, default='pending', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='partner.operator')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='OperatorTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('debit', 'Debit (bet)'), ('credit', 'Credit (win)'), ('rollback', 'Rollback')], db_index=True, max_length=10)),
                ('tx_ref', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency_code', models.CharField(default='GHS', max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retries', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='partner.operator')),
                ('operator_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='partner.operatorplayer')),
                ('operator_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='partner.operatorsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperatorWebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField(help_text='URL to receive webhook events')),
                ('subscribed_events', models.JSONField(default=list, help_text='List of event types to send')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_config', to='partner.operator')),
            ],
            options={
                'verbose_name': 'Webhook Config',
                'verbose_name_plural': 'Webhook Configs',
            },
        ),
        migrations.CreateModel(
            name='OperatorWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(db_index=True, max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('retries', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='partner.operator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='operatorplayer',
            index=models.Index(fields=['operator', 'ext_player_id'], name='partner_ope_operato_8822c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operatorplayer',
            unique_together={('operator', 'ext_player_id')},
        ),
        migrations.AlterUniqueTogether(
            name='operatorsettlement',
            unique_together={('operator', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='operatortransaction',
            index=models.Index(fields=['operator', 'tx_type', 'status'], name='partner_ope_operato_1030fe_idx'),
        ),
    ]
