# Generated by Django 5.2.9 on 2026-02-17 06:25

import secrets
from django.db import migrations


def seed_elitebet(apps, schema_editor):
    Operator = apps.get_model('partner', 'Operator')
    OperatorBranding = apps.get_model('partner', 'OperatorBranding')
    OperatorGameConfig = apps.get_model('partner', 'OperatorGameConfig')
    OperatorAPIKey = apps.get_model('partner', 'OperatorAPIKey')
    Currency = apps.get_model('game', 'Currency')

    # Get GHS currency
    ghs = Currency.objects.filter(code='GHS').first()
    if not ghs:
        return  # Currency not seeded yet — skip silently

    # Create operator
    operator, created = Operator.objects.get_or_create(
        slug='elitebet',
        defaults={
            'name': 'Elitebet',
            'website': 'https://elitebetgh.com',
            'status': 'active',
            'commission_percent': 20.00,
            'settlement_frequency': 'weekly',
            'min_settlement_amount': 100.00,
        }
    )

    if not created:
        return  # Already seeded

    # Create branding
    OperatorBranding.objects.create(
        operator=operator,
        display_name='Elitebet',
        primary_color='#1B5E20',
        accent_color='#4CAF50',
    )

    # Create game config
    OperatorGameConfig.objects.create(
        operator=operator,
        currency=ghs,
        house_edge_percent=60.00,
        min_stake=1.00,
        max_stake=1000.00,
        max_cashout=10000.00,
        zero_base_rate=0.0500,
        zero_growth_rate=0.0800,
        min_flips_before_zero=2,
        pause_cost_percent=10.00,
        max_session_duration_minutes=120,
        is_active=True,
    )

    # Generate API key
    api_key = f'cf_live_{secrets.token_hex(24)}'
    api_secret = secrets.token_hex(48)
    OperatorAPIKey.objects.create(
        operator=operator,
        label='Production Key',
        api_key=api_key,
        api_secret=api_secret,
        is_active=True,
        rate_limit_per_minute=120,
    )

    print(f'\n=== ELITEBET API CREDENTIALS ===')
    print(f'API Key:    {api_key}')
    print(f'API Secret: {api_secret}')
    print(f'================================\n')


def reverse_seed(apps, schema_editor):
    Operator = apps.get_model('partner', 'Operator')
    Operator.objects.filter(slug='elitebet').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
        ('game', '0003_sitebranding'),
    ]

    operations = [
        migrations.RunPython(seed_elitebet, reverse_seed),
    ]
